# Generated by Django 4.0.6 on 2022-08-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cousts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
                ('payTime', models.DateTimeField()),
                ('category_name', models.CharField(max_length=40)),
                ('Recipient', models.CharField(max_length=255)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('invoice', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Cousts',
            },
        ),
    ]
