# Generated by Django 4.0.6 on 2022-08-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cousts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousts',
            name='AccountNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cousts',
            name='invoice',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cousts',
            name='payTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cousts',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
