# Generated by Django 4.0.6 on 2022-08-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cousts', '0002_alter_cousts_accountnumber_alter_cousts_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousts',
            name='Recipient',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
