# Generated by Django 4.0.6 on 2022-08-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cousts', '0003_alter_cousts_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cousts',
            name='AccountNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cousts',
            name='Recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cousts',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
